### ISSUE TITLE
Roadmap for different store support

### ISSUE THREAD

**Issue by czocher** [maxcountryman/axum-login#78]
Hello @maxcountryman,
In connection with our discussion under #73 I'd like to propose a roadmap for changes required to this crate to support multiple different database/store backends in a way that they won't conflict with one another.

# Steps
- [ ] Migrate all the core (non-store related) code to a separate `axum-login-core` sub-crate in this repository. The `MemoryStore` can either be left in the `axum-login-core` sub-crate or extracted to a separate sub-crate (e.g. `axum-login-memory`) to serve as an example for further store implementations. I'd like your decision for this point @maxcountryman.
- [ ] Migrate all the `sqlx` related code to a `axum-login-sqlx` sub-crate.
- [ ] The `axum-login-tests` sub-crates will be divided per store sub-crate (currently most of them will go to `axum-login-sqlx`).
- [ ] The `examples` sub-crate shall be left as-is without any major structural changes (except imports).
- [ ] Publish the `axum-login-core` and `axum-login-sqlx` crates separately on `crates.io`.
- [ ] The current `axum-login` crate should probably be yanked from `crates.io` with information how to migrate to the new crates.
- [ ] Document how to implement new stores (with examples).

In the future all the new store implementations shall be created as sub-crates in the `axum-login` workspace.

Additional info: The crate naming I proposed follows the same structure that `axum` has.

**Comment by DrewMcArthur** [comment]
@czocher i just opened up #83, which creates a new sub-crate `axum-login-libsql`.  does that look like what you have in mind, as far as new implementations? i didn't touch any of the core/sqlx separation.  

i did still have sqlite system library conflicts, and had to upgrade `sqlx` to 0.7, but i think the cause of that is the test crate, which tries to compile everything? or does the workspace itself try to compile all of the crates together?

anyways, many thanks to you & @maxcountryman for all your work maintaining these crates!

**Comment by czocher** [comment]
@DrewMcArthur yep, looks more-or-less like what I have in mind. I'll need to do a deeper analysis to confirm it though. If there will be any changes they'll probably be very limited though.

**Comment by maxcountryman** [comment]
Now that we're not bundling user stores, I think it's safe to close this?

**Comment by czocher** [comment]
I believe so @maxcountryman.
